<?php
$wp_user_options_signin_form = array(
    array(
        'type' => 'text',
        'meta_key' => 'wp_user_email_name',
        'label' => __('Username or Email', 'wpuser'),
        'description' => '',
        'is_required' => 1,
        'icon' => 'fa-user',
        'default_value' => '',
        'placeholder' => __('Enter Username or Email or Mobile Number', 'wpuser'),
    ),
    array(
        'type' => 'password',
        'meta_key' => 'wp_user_password',
        'label' => __('Password', 'wpuser'),
        'description' => '',
        'is_required' => 0,
        'icon' => 'fa-lock',
        'default_value' => '',
        'placeholder' => __('Enter Password', 'wpuser'),
    ),
);

$wp_user_options_signup_form = array(
    array(
        'type' => 'text',
        'meta_key' => 'user_login',
        'label' => __('Username', 'wpuser'),
        'description' => '',
        'is_required' => 1,
        'icon' => 'fa-user',
        'default_value' => '',
        'placeholder' => __('Enter Username', 'wpuser'),
    ),
    array(
        'type' => 'text',
        'meta_key' => 'user_email',
        'label' => __('Email', 'wpuser'),
        'description' => '',
        'is_required' => 1,
        'icon' => 'fa-envelope',
        'default_value' => '',
        'placeholder' => __('Enter Email', 'wpuser'),
    ),
    array(
        'type' => 'password',
        'meta_key' => 'user_pass',
        'label' => __('Password', 'wpuser'),
        'description' => '',
        'is_required' => 1,
        'icon' => 'fa-lock',
        'default_value' => '',
        'placeholder' => __('Enter Password', 'wpuser'),
    ),
    array(
        'type' => 'password',
        'meta_key' => 'confirm_pass',
        'label' => __('Confirm Password', 'wpuser'),
        'description' => '',
        'is_required' => 1,
        'icon' => 'fa-log-in',
        'default_value' => '',
        'placeholder' => __('Confirm Password', 'wpuser'),
    ),
);

    $wp_user_options_forgot_form = array(
        array(
            'type' => 'text',
            'meta_key' => 'wp_user_email',
            'label' => __('Email', 'wpuser'),
            'description' => '',
            'is_required' => 1,
            'icon' => 'fa-envelope',
            'default_value' => '',
            'placeholder' => __('Enter Email', 'wpuser'),
        ),
    );

$wp_user_login_password_valid_message = (isset($wp_user_login_limit_password_enable) && $wp_user_login_limit_password_enable==1 && isset($wp_user_login_limit_password)) ?
    get_option('wp_user_login_password_valid_message') : '';

$wp_user_options_my_profile_form = array(
    array(
        'type' => 'image_upload',
        'meta_key' => 'user_meta_image',
        'label' => __('User Avatar', 'wpuser'),
        'description' => 'Upload an image or enter url for your user profile.',
        'is_required' => 0,
        'icon' => 'fa-image',
        'default_value' => '',
        'placeholder' => __('Upload an image or enter url for your user profile.', 'wpuser'),
        'weight_val' => 20,
    ),
    array(
        'type' => 'text',
        'meta_key' => 'first_name',
        'label' => __('First Name', 'wpuser'),
        'description' => '',
        'is_required' => 0,
        'icon' => 'fa-user',
        'default_value' => '',
        'placeholder' => __('Enter First Name', 'wpuser'),
        'weight_val' => 15,
    ),
    array(
        'type' => 'text',
        'meta_key' => 'last_name',
        'label' => __('Last Name', 'wpuser'),
        'description' => '',
        'is_required' => 0,
        'icon' => 'fa-user',
        'default_value' => '',
        'placeholder' => __('Enter Last Name', 'wpuser'),
        'weight_val' => 15,
    ),
    array(
        'type' => 'text',
        'meta_key' => 'user_email',
        'label' => __('Email', 'wpuser'),
        'description' => '',
        'is_required' => 1,
        'icon' => 'fa-envelope',
        'default_value' => '',
        'placeholder' => __('Enter Email', 'wpuser'),
        'weight_val' => 30,
    ),
    array(
        'type' => 'text',
        'meta_key' => 'user_url',
        'label' => __('Website', 'wpuser'),
        'description' => '',
        'is_required' => 0,
        'icon' => 'fa-globe',
        'default_value' => '',
        'placeholder' => __('Enter URL', 'wpuser'),
        'weight_val' => 10,
    ),
    array(
        'type' => 'password',
        'meta_key' => 'user_pass',
        'label' => __('Password', 'wpuser'),
        'description' => $wp_user_login_password_valid_message,
        'is_required' => 0,
        'icon' => 'fa-lock',
        'default_value' => '',
        'placeholder' => __('Enter Password', 'wpuser'),
    ),
    array(
        'type' => 'password',
        'meta_key' => 'confirm_pass',
        'label' => __('Confirm Password', 'wpuser'),
        'description' => '',
        'is_required' => 0,
        'icon' => 'fa-log-in',
        'default_value' => '',
        'placeholder' => __('Confirm Password', 'wpuser'),
    ),
    array(
        'type' => 'textarea',
        'meta_key' => 'description',
        'label' => __('Description', 'wpuser'),
        'description' => '',
        'is_required' => 0,
        'icon' => 'fa-log-in',
        'default_value' => '',
        'placeholder' => __('Description', 'wpuser'),
        'weight_val' => 10,
    ),
);
